version: 2

jobs:
    build:
        branches:
            only:
                - unit-refactor

        docker:
            - image: circleci/buildpack-deps:testing

        steps:
            - checkout
            - run:
                command: |
                    sudo sh -c 'echo "deb http://ftp.es.debian.org/debian/ experimental main" >> /etc/apt/sources.list'
                    sudo apt-get update -y
                    sudo apt-get install -y -q --no-install-recommends libgtk2.0-dev libpcap-dev libjpeg-dev libgif-dev libpng-dev libcmocka-dev
                    sudo apt-get install -y -q --no-install-recommends -t experimental libwebsockets-dev

            - run:
                command: |
                    autoreconf -fi
                    ./configure --disable-silent-rules

            - run:
                command: |
                    set +e
                    make coverage
                    eval "bash <(curl -s https://codecov.io/bash); exit $?"

            - store_artifacts:
                path: src/media/test-suite.log
